import streamlit as st
from langchain_groq import ChatGroq
from langchain_community.utilities import ArxivAPIWrapper, WikipediaAPIWrapper
from langchain_community.tools import ArxivQueryRun, WikipediaQueryRun, DuckDuckGoSearchResults #Helps in performing live searches
from langchain.agents import initialize_agent, AgentType
from langchain.callbacks import StreamlitCallbackHandler  #Used to display thoughts and actions by an agent in a streamlit app
import os 
from dotenv import load_dotenv

arxiv_wrapper = ArxivAPIWrapper(top_k_results=1, doc_content_chars_max=1250)
arxiv = ArxivQueryRun(api_wrapper=arxiv_wrapper)

wiki_wrapper = WikipediaAPIWrapper(top_k_results=1, doc_content_chars_max=1250)
wiki = WikipediaQueryRun(api_wrapper=wiki_wrapper)

search = DuckDuckGoSearchResults(name = "Search")

st.title("Langchain - Chat with Search")

st.sidebar.title("Settings")
api_key = st.sidebar.text_input("Enter GROQ API KEY: ", type="password")

if "messages" not in st.session_state:  #checker if message is in the given state
    st.session_state["messages"] =[
        {"role":"assistant", "content":"Hi, I'm a chatbot who can search the web.Help?"}
    ]

for msg in st.session_state.messages:
    st.chat_message(msg["role"]).write(msg['content']) #st.chat)messages-> create a chat bubble, .write is used to write all the chat history content in that bubble  

if prompt:=st.chat_input(placeholder="What is Machine Learning?") : #:= ->both assigns the input to prompt and checks if the user typed something 
    #If giving and api_key, it is taking it also as a prompt and displaying api key also
    st.session_state.messages.append({"role":"user", "content":prompt}) #if types then new dictionary is appended to the messages
    st.chat_message("user").write(prompt) #creates a chat bubble and enters the prompt in that bubble 

    llm = ChatGroq(groq_api_key = api_key, model_name ="llama-3.3-70b-versatile", streaming=True) #Streaming true, write the output as generated by model, instead of waiting for the output generation get finished first
    tools = [search, arxiv, wiki]

    search_agent = initialize_agent(tools, llm, agent=AgentType.ZERO_SHOT_REACT_DESCRIPTION, handling_parsing_errors=True) #it gives output based on the given input, without relying on the previous chat history
    #Agent Executor -> search_agent
    with st.chat_message("assistant"):
        st_cb=StreamlitCallbackHandler(st.container(), expand_new_thoughts=False)
        response = search_agent.run(st.session_state.messages, callbacks=[st_cb])
        st.session_state.messages.append({'role':'assistant','content':response})
        st.write(response)


# Value error coming due to conflict between AgentExecutor, where it expects all data and then search in it, but streaming giving
# only chunk of data, which seems irrelevant to it, so giving Value Error

